Fix grcov download link
OxideEngine/Oxide pull request #32
Opened 2022-03-30 05:50 UTC by you4rin

## Details

This PR includes following fixes:
- grcov download link

2022-03-30 06:02 UTC, BeLeap requested changes

2022-03-30 06:02 UTC, BeLeap commented on .github/workflows/test.yml
> +        run: curl -L https://github.com/mozilla/grcov/releases/download/v0.8.7/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
```suggestion
        run: curl -L https://github.com/mozilla/grcov/releases/download/latest/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
```

면 작동안하나요?

2022-03-30 06:04 UTC, you4rin commented on .github/workflows/test.yml
> +        run: curl -L https://github.com/mozilla/grcov/releases/download/v0.8.7/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
한 번 해볼게요

2022-03-30 06:05 UTC, you4rin commented on .github/workflows/test.yml
> +        run: curl -L https://github.com/mozilla/grcov/releases/download/v0.8.7/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
일단 링크 들어갔을땐 404 뜨는거보면.. 안될거같네요. 푸시 괜히한듯

2022-03-31 10:16 UTC, BeLeap approved these changes

2022-04-03 12:08 UTC, utilForever approved these changes
LGTM. ✈️

2022-04-03 12:10 UTC, merged